// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Data;

#nullable disable

namespace LeafAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260630223916_AddIntegrations")]
    partial class AddIntegrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("IntegrationSequence");

            modelBuilder.Entity("LeafAPI.Interfaces.Integration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"IntegrationSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WebAPI.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("WebAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebAPI.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedToUserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToUserName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChangedByUserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedByUserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("ColumnIdx")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("BoardId", "ColumnIdx", "Position");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("WebAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgedByUserEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebAPI.Models.NotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("WebAPI.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WebAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomePage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LeafAPI.Models.InfinitePayIntegration", b =>
                {
                    b.HasBaseType("LeafAPI.Interfaces.Integration");

                    b.HasIndex("BoardId");

                    b.HasIndex("LeadId");

                    b.ToTable("InfinitePayIntegrations");
                });

            modelBuilder.Entity("LeafAPI.Models.LoggiIntegration", b =>
                {
                    b.HasBaseType("LeafAPI.Interfaces.Integration");

                    b.HasIndex("BoardId");

                    b.HasIndex("LeadId");

                    b.ToTable("LoggiIntegrations");
                });

            modelBuilder.Entity("WebAPI.Models.Board", b =>
                {
                    b.OwnsOne("LeafAPI.Interfaces.IntegrationSetting", "InfinitePaySetting", b1 =>
                        {
                            b1.Property<int>("BoardId")
                                .HasColumnType("integer");

                            b1.Property<bool>("AllowBypassRules")
                                .HasColumnType("boolean");

                            b1.Property<int>("DestinationColumn")
                                .HasColumnType("integer");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean");

                            b1.HasKey("BoardId");

                            b1.ToTable("Boards");

                            b1.WithOwner()
                                .HasForeignKey("BoardId");
                        });

                    b.OwnsOne("LeafAPI.Interfaces.IntegrationSetting", "LoggiSetting", b1 =>
                        {
                            b1.Property<int>("BoardId")
                                .HasColumnType("integer");

                            b1.Property<bool>("AllowBypassRules")
                                .HasColumnType("boolean");

                            b1.Property<int>("DestinationColumn")
                                .HasColumnType("integer");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("boolean");

                            b1.HasKey("BoardId");

                            b1.ToTable("Boards");

                            b1.WithOwner()
                                .HasForeignKey("BoardId");
                        });

                    b.OwnsMany("WebAPI.Models.Column", "Columns", b1 =>
                        {
                            b1.Property<int>("BoardId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BoardId", "__synthesizedOrdinal");

                            b1.ToTable("Boards");

                            b1.ToJson("Columns");

                            b1.WithOwner()
                                .HasForeignKey("BoardId");
                        });

                    b.Navigation("Columns");

                    b.Navigation("InfinitePaySetting")
                        .IsRequired();

                    b.Navigation("LoggiSetting")
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.Models.Lead", b =>
                {
                    b.HasOne("WebAPI.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebAPI.Models.Payment", b =>
                {
                    b.HasOne("WebAPI.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.HasOne("WebAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LeafAPI.Models.InfinitePayIntegration", b =>
                {
                    b.HasOne("WebAPI.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LeafAPI.Interfaces.Webhook", "Webhook", b1 =>
                        {
                            b1.Property<int>("InfinitePayIntegrationId")
                                .HasColumnType("integer");

                            b1.Property<string>("PayloadReceived")
                                .HasColumnType("jsonb");

                            b1.Property<DateTime>("PayloadReceivedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RequestSent")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("ResponsePayload")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ResponseStatus")
                                .HasColumnType("integer");

                            b1.HasKey("InfinitePayIntegrationId");

                            b1.ToTable("InfinitePayIntegrations");

                            b1.WithOwner()
                                .HasForeignKey("InfinitePayIntegrationId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Lead");

                    b.Navigation("Webhook")
                        .IsRequired();
                });

            modelBuilder.Entity("LeafAPI.Models.LoggiIntegration", b =>
                {
                    b.HasOne("WebAPI.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LeafAPI.Interfaces.Webhook", "Webhook", b1 =>
                        {
                            b1.Property<int>("LoggiIntegrationId")
                                .HasColumnType("integer");

                            b1.Property<string>("PayloadReceived")
                                .HasColumnType("jsonb");

                            b1.Property<DateTime>("PayloadReceivedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RequestSent")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("ResponsePayload")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("ResponseStatus")
                                .HasColumnType("integer");

                            b1.HasKey("LoggiIntegrationId");

                            b1.ToTable("LoggiIntegrations");

                            b1.WithOwner()
                                .HasForeignKey("LoggiIntegrationId");
                        });

                    b.Navigation("Board");

                    b.Navigation("Lead");

                    b.Navigation("Webhook")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
